### ISSUE TITLE
Not open settings.

### ISSUE THREAD

**Issue by andigenn** [hwtnb/SylphyHornPlusWin11#1]
Hi, when I try to open the settings this warning appears and I can't open them (Windows 11 Pro Insider Preview build 22526.1000):

"System.NotSupportedException: You must target Windows 10 in your app.manifest and run without debugging.
in WindowsDesktop.VirtualDesktopHelper.ThrowIfNotSupported()
in WindowsDesktop.VirtualDesktop.GetDesktops()
in SylphyHorn.Services.SettingsService.ResizeList()
in SylphyHorn.Services.HookService.Suspend()
in SylphyHorn.ApplicationPreparation.g__ShowSettings|15_0()
in System.Windows.Forms.MenuItem.OnClick(EventArgs e)
in System.Windows.Forms.MenuItem.MenuItemData.Execute()
in System.Windows.Forms.Command.Invoke()
in System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)"

![148808040-f9dca361-8b96-4a58-a212-a73151d48da9](https://user-images.githubusercontent.com/17638454/149235922-3b39fa5a-bb12-4737-861f-a270549082cb.png)

**Comment by hwtnb** [comment]
@andigenn Thank you for your report.

This is a bug of VirtualDesktop library, rather than of SylphyHorn. I try to fix it now.
Please try the test binary (it worked on build 22533 and 22538), the link is here: https://github.com/hwtnb/SylphyHornPlusWin11/releases/download/v4.0.0-beta.3/SylphyHornPlus-Ver4.0.0-beta.3-fix11Insider.zip

Note: delete cache data (VirtualDesktop.*****.generated.dll) at %UserProfile%\AppData\Local\grabacr.net\SylphyHorn\assemblies before startup.

On recent Windows 11 Insider Preview, SylphyHorn cannot get COM IID at rumtime. It may be difficult to support newer builds if virtual desktop COM API (CLSID or IID) is changed.

**Comment by andigenn** [comment]
Wow! It works fine on Win 11 build 22538.1010 rs_prerelease. Tnx a lot for your work!

**Comment by hwtnb** [comment]
@andigenn Thanks for your test.

I have released [beta.4](https://github.com/hwtnb/SylphyHornPlusWin11/releases/tag/v4.0.0-beta.4).
I will close this issue if no problem occurs.
