### ISSUE TITLE
Window from last switched desktop focused when switching to another desktop

### ISSUE THREAD

**Issue by mintyleaf** [hwtnb/SylphyHornPlusWin11#5]
Hello!
When i switch to another desktop - there are no windows focused, so i need to manually press alt+tab or click window by mouse to start it grab input (like browser, terminal e.t.c.)

Using 4.0.0 beta 5 on Windows 11 Pro 21H2

**Comment by mintyleaf** [comment]
after some usage i just found that when switching desktop the last focused windows from switched desktop simply remains focused
that way, i'm often accidently typing something in address bar of chrome from switched desktop, and to code editor vice versa =D

**Comment by hwtnb** [comment]
@mintyleaf Thanks for your report.

It is not easy to fix the issue completely because of foreground restriction on Windows (https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow#remarks).
But I have made good progress. I would appreciate that you test the below binary because the desktop state (e.g. what applcations are running) is relevant to the issue.
https://github.com/hwtnb/SylphyHornPlusWin11/releases/download/v4.0.0-beta.5/SylphyHornPlus-Ver4.0.0-beta.5-fixWindowFocus.zip

There is a performance issue when switching desktops very frequently and quickly (less 1s).
It is difficult to avoid performance degradation, although it seems to be little problem in practical use.

**Comment by mintyleaf** [comment]
> @mintyleaf Thanks for your report.
> 
> It is not easy to fix the issue completely because of foreground restriction on Windows ([docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow#remarks](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow#remarks)). But I have made good progress. I would appreciate that you test the below binary because the desktop state (e.g. what applcations are running) is relevant to the issue. [`v4.0.0-beta.5` SylphyHornPlus-Ver4.0.0-beta.5-fixWindowFocus.zip (download)](https://github.com/hwtnb/SylphyHornPlusWin11/releases/download/v4.0.0-beta.5/SylphyHornPlus-Ver4.0.0-beta.5-fixWindowFocus.zip)
> 
> There is a performance issue when switching desktops very frequently and quickly (less 1s). It is difficult to avoid performance degradation, although it seems to be little problem in practical use.

tested it out - now it's working like a charm
yeah, seems like there is performance issue when quick switching (which is really not issue for practical use)

**Comment by hwtnb** [comment]
@mintyleaf Thanks for your contribution!

I will commit the fix before long.

**Comment by hwtnb** [comment]
I have released [beta.6](https://github.com/hwtnb/SylphyHornPlusWin11/releases/tag/v4.0.0-beta.6), so the issue is closed.
